# Generated by Django 4.2.15 on 2024-09-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='post_rating',
        ),
    ]
